name: dart_promise
description: "Dart Promise. A simple implementation of the Promise pattern in Dart."
version: 0.0.1
repository: https://github.com/iamngoni/dart_promise
homepage: https://github.com/iamngoni/dart_promise

environment:
  sdk: '>=3.5.0-160.0.dev <4.0.0'

dev_dependencies:
  test: 1.25.7
  very_good_analysis: ^5.0.1